const { withPodfile } = require('@expo/config-plugins');

// ---------------------------------------------------------------------------
// Why this plugin exists
// ---------------------------------------------------------------------------
// With the upstream podspec restored (d798640), MdocDataTransfer.podspec's two
// spm_dependency(...) calls attach MdocSecurity18013 and WalletStorage to the
// pod target, and ios.buildStatic makes that target build as
// libMdocDataTransfer.a instead of a .framework. That combination fixed module
// visibility and build ordering outright — run 32290492567 has zero "no such
// module" errors — but it still failed at the final link with 15,628 duplicate
// symbols.
//
// Every one of those is now *intra-archive*: both copies live inside
// libMdocDataTransfer.a. (Before d798640 removed the app-target injection, the
// pairs were app-copy vs pod-archive; that half is gone.)
//
//   duplicate symbol '...' in:
//       .../libMdocDataTransfer.a[49](X509.o)
//       .../libMdocDataTransfer.a[26](X509.o)
//
// The index delta is exactly -23 for every pair, and the pod's libtool line
// passes exactly 23 SPM object files. That is the same fingerprint the original
// podspec comment recorded before any of this work started, so buildStatic
// changed the container (.a instead of .framework) without changing the
// double-feed:
//
//   libtool -static ... \
//     -filelist .../MdocDataTransfer.LinkFileList \   <- 23 SPM objects, copy 1
//     .../Release-iphoneos/X509.o \                   <- 23 SPM objects, copy 2
//     ... 22 more explicit .o arguments ...
//     -o .../libMdocDataTransfer.a
//
// Xcode contributes the SPM objects twice: once by writing them into the
// target's LinkFileList, and once as explicit arguments because the target
// resolves those package products. The explicit arguments are generated by
// Xcode's SPM handling and are not driven by any build setting we can edit, so
// the tractable half is the other one — the Frameworks build phase entries that
// put them in the LinkFileList.
//
// ---------------------------------------------------------------------------
// The fix
// ---------------------------------------------------------------------------
// Drop the SPM product entries from the pod target's Frameworks build phase
// while leaving package_product_dependencies intact. The declaration is what
// gives Xcode the build-order edge and the module search path (both verified
// working in run 32290492567); the Frameworks phase is only about linking, and
// its contribution here is redundant with the explicit arguments libtool
// already receives.
//
// This runs after react_native_post_install for the same reason the earlier
// hook did: SPM.apply_on_post_install rebuilds these dependencies during that
// call, so editing before it would be undone.
// ---------------------------------------------------------------------------

const POD_TARGET = 'MdocDataTransfer';
const SPM_PRODUCTS = ['MdocSecurity18013', 'WalletStorage'];

// Anchor after the react_native_post_install(...) call — CocoaPods rejects a
// second post_install hook ("Specifying multiple post_install hooks is
// unsupported"), and SPM.apply_on_post_install runs inside that helper.
const ANCHOR = /(\n(\s*)react_native_post_install\([\s\S]*?\n\2\))/;

const HOOK = `
    # >>> withMdocSpmNoDoubleLink (managed by plugins/withMdocSpmNoDoubleLink.js)
    # Remove the Swift package products from ${POD_TARGET}'s Frameworks build
    # phase. They stay in package_product_dependencies, so Xcode keeps the
    # build-order edge and the module search path; only the redundant *link*
    # entry goes away.
    #
    # Without this, libtool receives each of the 23 resolved SPM objects twice —
    # once via MdocDataTransfer.LinkFileList and once as an explicit argument
    # Xcode adds for the resolved package products — producing an archive with
    # two full copies of the dependency closure and 15,628 duplicate symbols at
    # the final app link (run 32290492567, index deltas all exactly -23).
    mdoc_spm_products = ${JSON.stringify(SPM_PRODUCTS).replace(/"/g, "'")}
    mdoc_pod_target = installer.pods_project&.targets&.find { |t| t.name == '${POD_TARGET}' }

    if mdoc_pod_target.nil?
      raise "[mdoc-spm-nodouble] Pod target '${POD_TARGET}' not found in Pods.xcodeproj."
    end

    removed = 0
    mdoc_pod_target.frameworks_build_phase.files.dup.each do |build_file|
      product_ref = build_file.product_ref
      next if product_ref.nil?
      next unless mdoc_spm_products.include?(product_ref.product_name)

      mdoc_pod_target.frameworks_build_phase.remove_build_file(build_file)
      removed += 1
      Pod::UI.puts "[mdoc-spm-nodouble] Unlinked '#{product_ref.product_name}' from ${POD_TARGET}'s Frameworks phase (still declared, still ordered)."
    end

    if removed.zero?
      Pod::UI.warn "[mdoc-spm-nodouble] No SPM products were linked in ${POD_TARGET}'s Frameworks phase; " \\
                   "either CocoaPods/Xcode changed how spm_dependency links products, or the duplicate " \\
                   "objects now come from somewhere else. Re-check the libtool line before trusting this."
    end
    # <<< withMdocSpmNoDoubleLink
`;

module.exports = function withMdocSpmNoDoubleLink(config) {
  return withPodfile(config, (cfg) => {
    const contents = cfg.modResults.contents;

    if (contents.includes('withMdocSpmNoDoubleLink')) {
      return cfg;
    }

    if (!ANCHOR.test(contents)) {
      throw new Error(
        'withMdocSpmNoDoubleLink: could not find the react_native_post_install(...) call in the ' +
          'generated Podfile. The hook must run after it, because SPM.apply_on_post_install ' +
          'rebuilds the pod\'s package product dependencies during that call. The Expo template ' +
          'changed — update the anchor.'
      );
    }

    cfg.modResults.contents = contents.replace(ANCHOR, `$1\n${HOOK}`);
    return cfg;
  });
};
